# ANSI color codes
COLOR_RED := "\\033[0;31m"
COLOR_GREEN := "\\033[0;32m"
COLOR_YELLOW := "\\033[0;33m"
COLOR_BLUE := "\\033[0;34m"
COLOR_RESET := "\\033[0m"
BOLD := "\\033[1m"

_default:
    @just -g --list
